# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build and test the python package
on:
  push:
    branches:
      - 'releases/**'
jobs: 
  build:
    name: Build whl from source
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Fetch git tags from origin
      run: git fetch --tags origin

    - name: Install build and wheel packages
      run: >-
        python -m
        pip install
        build wheel
        --user

    - name: Build wheel and source distribution
      run: |
        echo `pwd`
        echo `git describe --tags`
        python -m build --wheel --sdist

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-pip-whl
        path: |
          dist

  test-the-wheel:
    name: Install whl and run demo
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      id: github_context_step
      run: echo '${{ toJSON(github) }}'

    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Download build artifacts
      uses: actions/download-artifact@v4.1.7
      with:
        name: dist-pip-whl

    - name: Install tensorboardX from wheel
      run: pip install tensorboardx*.whl

    - name: Install torch torchvision for demo
      run: pip install torch torchvision

    - name: Print version
      run: python -c "import tensorboardX; print(tensorboardX.__version__)"

    - name: Run examples
      run: |
        cd examples
        python demo.py

    - name: Archive demo artifacts
      uses: actions/upload-artifact@v4
      with:
        name: demo-results
        path: |
          examples/runs

